FROM openjdk:8

RUN mkdir -p /logs && chmod 777 /logs

# 复制应用文件
COPY ap-worker.jar startApWorker.sh  ./
COPY config/bootstrap.yml ./config/

# 执行权限
RUN chmod +x ./startApWorker.sh \
    && chmod 644 ./ap-worker.jar ./config/bootstrap.yml

EXPOSE 10006

CMD ["./startApWorker.sh"]