FROM openjdk:8

# 提前创建目录
RUN mkdir -p /spp/config /spp/logs && chmod 777 /spp/logs

# 复制应用文件
COPY actuator.jar logback-spring.xml startActuator.sh  /spp/
COPY config/bootstrap.yml /spp/config/

# 脚本执行权限
RUN chmod +x /spp/startActuator.sh \
    && chmod 644 /spp/actuator.jar /spp/config/bootstrap.yml /spp/logback-spring.xml

EXPOSE 18093

CMD ["/spp/startActuator.sh"]