FROM openjdk:8

RUN mkdir -p /spp/logs && chmod 777 /spp/logs

# 复制应用文件
COPY kafka.jar startKafka.sh  /spp/
COPY config/bootstrap.yml /spp/config/

# 执行权限
RUN chmod +x /spp/startKafka.sh \
    && chmod 644 /spp/kafka.jar /spp/config/bootstrap.yml

EXPOSE 18086

CMD ["/spp/startKafka.sh"]