FROM openjdk:8

RUN mkdir -p /logs && chmod 777 /logs

# 复制应用文件
COPY kafka.jar startKafka.sh  ./
COPY config/bootstrap.yml ./config/

# 执行权限
RUN chmod +x ./startKafka.sh \
    && chmod 644 ./kafka.jar ./config/bootstrap.yml

EXPOSE 18086

CMD ["./startKafka.sh"]