FROM openjdk:8

RUN mkdir -p /logs && chmod 777 /logs

# 复制应用文件
COPY spp-admin.jar startSppAdmin.sh  ./
COPY config/bootstrap.yml ./config/

# 执行权限
RUN chmod +x ./startSppAdmin.sh \
    && chmod 644 ./spp-admin.jar ./config/bootstrap.yml

EXPOSE 10003

CMD ["./startSppAdmin.sh"]