FROM openjdk:8

RUN mkdir -p /spp/logs && chmod 777 /spp/logs

# 复制应用文件
COPY spp-admin.jar startSppAdmin.sh  /spp/
COPY config/bootstrap.yml /spp/config/

# 执行权限
RUN chmod +x /spp/startSppAdmin.sh \
    && chmod 644 /spp/spp-admin.jar /spp/config/bootstrap.yml

EXPOSE 10003

CMD ["/spp/startSppAdmin.sh"]